### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by Butterroach**
one character change (very revolutionary pr)

### CODE REVIEW

**Comment by Butterroach** [comment]
society if you merge this pr

future

**Comment by artifishvr** [comment]
i cant spell spahettti

**Comment by Butterroach** [comment]
you could've merged and made the world a much better place for everyone but instead you decided to close it?! how DARE you

**Comment by artifishvr** [comment]
i am a multibillionare

**Comment by Butterroach** [comment]
i will make you a multi

**Comment by Butterroach** [comment]
i accidentally sent

**Comment by OcaMinty** [comment]
multibillionare more like multi badlion launcher or something i dont have a pun im going to kill m

**Comment by Butterroach** [comment]
oca do all the work now

**Comment by OcaMinty** [comment]
im hacking into the mainframe rn

**Comment by Butterroach** [comment]
holy shit i can reopne

**Comment by Butterroach** [comment]
im being too silly

**Comment by OcaMinty** [comment]
im going to delete this message

**Comment by artifishvr** [comment]
why was there feet in the professional spongedsc org

**Comment by OcaMinty** [comment]
no there wasnt.

**Comment by Butterroach** [comment]
https://github.com/spongedsc/SpongeChat/assets/93810367/16b0aab6-c046-42c6-90b4-e6aaa4cdc816

**Pull request closed without merging**
