### PR TITLE
[enhancement] let spongy wongy know if the reply is from itself or another user

### PR DESCRIPTION
**Pull request by Butterroach**
I can't test this lmao

### CODE REVIEW

**Comment by Butterroach** [comment]
Extra funny image
Screenshot_20240417_214753_ChatGPT

**Review by artifishvr — APPROVED** [review]
LGTM

**Comment by Butterroach** [comment]
What the fuck does LGTM mean

**Comment by artificialbutter** [comment]
looks good to me

**Comment by Butterroach** [comment]
Ok

**Pull request merged**
