### PR TITLE
[v1] Implement Zustand to fix history states

### PR DESCRIPTION
**Pull request by daniwasonline**
A really wack way of fixing the %reset command, but I implemented Zustand (a _**React-made**_ agnostic global state manager) to properly handle the conversation history. It actually works?

E: I also added a %messages command to track the amount of messages stored in Zustand for debugging purposes.

### CODE REVIEW

**Review by Butterroach — APPROVED** [review]
yeah idk what you're doing

**Comment by daniwasonline** [comment]
> yeah idk what you're doing

yeah me neither

**Review by artifishvr — APPROVED** [review]
looks so overkilll but ok yeah lgtm

**Comment by Butterroach** [comment]
playgrtound

**Pull request merged**
