### PR TITLE
lowercase image descriptions

### PR DESCRIPTION
**Pull request by Butterroach**
so it's more consistent with the start of it fuckcick

### CODE REVIEW

**Comment by Butterroach** [comment]
extra funny image that'll boost reviewing by 250x
image_proxy

**Comment by Butterroach** [comment]
that image is so large i am so sorry

**Comment by artifishvr** [comment]
this is literally unnecessary

**Review by artifishvr — APPROVED** [review]
you are annoying

**Comment by Butterroach** [comment]
:3

**Pull request merged**
